### ISSUE TITLE
Documentation link gives 404

### ISSUE THREAD

**Issue by lfbn** [resumic/schema#104]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
The full documentation link in README.md goes to the 404 github page.

**What you expected to happen**:
To show the full documentation.

**How to reproduce it (as minimally and precisely as possible)**:
Click in the full documentation link in README.md.

**Anything else we need to know?**:
No.

**Environment**:
- Resumic version:  
- OS:  All
- CLI version:  
- Others:

**Comment by stp-ip** [comment]
Thanks for reporting. I went ahead and removed the section from the README.

Once we have the schema and the first cli iteration done, docs should follow.

We are always happy for contributions, reviews or general feedback in the interim.
