### ISSUE TITLE
Project chat?

### ISSUE THREAD

**Issue by jahzielv** [resumic/schema#107]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

Would y'all be open to creating a Gitter/Discord/Slack or some other form of chat for Resumic? It might make lightweight conversations about new features or asking questions/quick communications easier, plus provide a way for the community to give feedback and participate. Totally understand if we wanna stick to Issues for right now, but just thought I'd throw the idea out! 😄

**Comment by stp-ip** [comment]
There is a basecamp, but we haven't publicly linked or pushed people there. For now I added a short link for the opt-in link: s.resumic.org/chat

Happy to iterate, if this makes sense in the long run as I find discord might be something better in terms of keeping information long term, but then we usually use issues for this.
