### ISSUE TITLE
Interesting view on CVs

### ISSUE THREAD

**Issue by stp-ip** [resumic/schema#113]
https://twitter.com/LargeCardinal/status/1168128486436954114

**Comment by pke** [comment]
As a consequence the schema should be relaxed and should only `"require": ["personal"]`

**Comment by stp-ip** [comment]
Personal has too much data so even, if we would go about relaxing it should not be personal but core that is the primary thing.

But agree that the requirement might not be necessary within the schema. Might be in the tooling to nudge about. Happy for your more detailed thoughts.

**Comment by pke** [comment]
Core then. I would be fine with that.

In general though I'd strongly favour evolving the schema over at JSONResume instead of having two "standards".

**Comment by stp-ip** [comment]
Sure. Not for lack of trying. As you saw I am still active at JSONResume and that since 2015.

As mentioned in various issues the plan was always to iterate outside JSONResume and later move this back into JSONResume and keep Resumic around as a Go implementation of it. If that works out is still up for debate :P
