### ISSUE TITLE
Document differences from JSONResume

### ISSUE THREAD

**Issue by KOLANICH** [resumic/schema#15]

**Comment by stp-ip** [comment]
We were a bit dead locked in JSONResume and didn't move forward. It seemed easier to iterate on a new schema with a clean start.
Resumic is a new project building on the schema work from JSONResume with a focus on the schema for now and later on reusing established projects for the surrounding tooling.
When we get to a state where the schema is in good state, we might be able to mold it back into JSONResume.

**Comment by KOLANICH** [comment]
Why can't that be done there?

**Comment by stp-ip** [comment]
One reason is that the current active maintainers don't have access to handle some things. That complicates the matter. Contacting the owners didn't work out. So resumic got created.
It's not trying to compete, the idea is more to supplement on the schema and build another opinionated stack of tooling, which can be more easily maintained.

**Comment by KOLANICH** [comment]
OK. Would you migrate the issues from JSONSchema?

**Comment by stp-ip** [comment]
We went through all issues from JSONResume once and integrated most of the changes into the latest schema here. We decided against a full issue migration to keep the clean slate of the repo. If you find something that isn't yet implemented in the schema, we are happy to look into it (aka open an issue with the link back to JSONResume) and we take a look.

**Comment by DandyDev** [comment]
Even though this isn't a literal fork of JSONResume, it _is_ building upon the work done by the JSONResume people, so I think the least you could do, is mention JSONResume in the README.

**Comment by stp-ip** [comment]
Wasn't intentionally forgotten in the README. It's already on the website, that it's based on the JSONResume work. Will add an issue to track.
