### ISSUE TITLE
Change "format" in certificates/score sub-section

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#16]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
In https://github.com/resumic/schema/blob/master/schema.json#L546 format "date" should be replaced.

**Comment by ss22ever** [comment]
@stp not sure of which format to use https://github.com/json-schema/json-schema/wiki/%22format%22-suggestions?

**Comment by stp-ip** [comment]
So byte is the format for data encoded. That is something we might use for project images later on. Either a link to an image or base64 encoded data so it actually is selfcontained. Will open an issue for the idea.

Here I think we can actually use no format at all. Then it's just a plain string without any checking done. That seems to be necessary here or?
