### ISSUE TITLE
Move to more consistent field documentation

### ISSUE THREAD

**Issue by stp-ip** [resumic/schema#2]
Currently there are 2 types of documentation.
* value proposition ("e.g. 2017-01-01")
* description ("A social weirdness company.")

We should move all descriptions to be actual field descriptions. What is the field about.

* [x] Set and document convention -> Capitalize first letter, declarative, ending in a dot.
* [x] Discuss possibility for an additional exampleValue field. Could be used in editor as placeholder?

Some things still in need for discussion:
* Move to declarative descriptions? (What is the field about?) -> "Definition for this companies activity."
* Move away from speaking directly to the user? -> "Select the location where you live at" -> "Current living location"

**Comment by ss22ever** [comment]
Well @stp-ip  I would say writing  `description ("eg. A social weirdness company.")`
will be a better option because `Definition for this companies activity.` looks quite misleading and confusing to the user.

**Comment by ss22ever** [comment]
@stp-ip I think where needed we could combine both declarative descriptions and an example.
eg. `"Definition for this companies activity, e.g  A social weirdness company. "`

**Comment by stp-ip** [comment]
Sounds reasonable. Then let's go with: "e.g. A social weirdness company [Company description]"
Does that sound good?

**Comment by stp-ip** [comment]
Considering that parsing the example might be a good idea...
What about:
"description": "Description of the companies primary activity",
"exampleValue": "A social weirdness company"

**Comment by ss22ever** [comment]
@stp-ip  use of example value sounds reasonable, but I would like to ask what is the need to parse them separately i.e why not both in one as in "Definition for this companies activity, e.g A social weirdness company."

**Comment by stp-ip** [comment]
Tools can more easily parse separate fields than parsing one field and then extracting/splitting it. That was my main reasoning. You think splitting it up into separate fields would clutter the schema too much?

**Comment by ss22ever** [comment]
@stp-ip Yes I think so that there is no point giving both of them a separate field name if the main aim of the description and example is just to acquaint the user but not for a theme specific use.What do you say?

**Comment by stp-ip** [comment]
Ok I can agree with that. So format like this:
"e.g. A social weirdness company - [Description of the companies primary activity]" or any other preference?

**Comment by stp-ip** [comment]
So 3 types:
1. for example only: "e.g. A social weirdness company"
  * e.g. at the beginning
  * no dot at the end

2. for example + description: "e.g. A social weirdness company - Description of the companies primary activity"
  * e.g. at the beginning
  * followed by "-"
  * first description character capitalized
  *  no dot at the end

3. description only - used for section description: "Work specific activities"
  * first description character capitalized
  *  no dot at the end

**Comment by ss22ever** [comment]
Yes.
As provided we  also need to discuss :
Move to declarative descriptions? (What is the field about?) -> "Definition for this companies activity."
Move away from speaking directly to the user? -> "Select the location where you live at" -> "Current living location"

**Comment by stp-ip** [comment]
Seems like we might be targeting more the developers with the schema than the developers. Basically moving from exposing the schema to be edited to a more non-developer friendly interface. This would suggest going more declarative, if you agree. Happy to hear your opinion.

**Comment by ss22ever** [comment]
Yes, even I agree with the same.But is it that for no case the schema descriptions can not be used as a default value in the input field of the editor, if yes, in that case, instruction type descriptions will be helpful.

**Comment by stp-ip** [comment]
The editor might be providing the context and the default value in the input field could be the example?

**Comment by ss22ever** [comment]
Ok, then going for more declarative declarations seems legit.
