### ISSUE TITLE
To Dos for validator

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#20]
Following is the list of things that needs to be added:

- [ ] return true/false on validate

- [ ] load files via packr valid, invalid, schema as package

- [ ] load schema from package in validate

- [ ] load valid/invalid in tests   

- [ ] tests checking all examples with validate

**Comment by stp-ip** [comment]
Splitting these up into their own issues makes referencing them in specific commits easier. Not 100% necessary, but makes intention of commits and specific todo/issue discussion cleaner. Also allows this to be split up into multiple PRs more easily.

**Comment by ss22ever** [comment]
Yes. I think you are saying it right.
Closing for # 25 , #26, #27, #28,#29 respectively.
