### ISSUE TITLE
schema.go: go lint shows warnings

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#24]
Golint shows some warnings suggesting as per conventions suggesting Url to be URL and IdNumber to be IDNumber.
Also affecting [goreportcard's](https://goreportcard.com/report/github.com/resumic/schema) result.

**Comment by stp-ip** [comment]
Within the schema file I assume? It's a Go convention and not specifically a json convention. I'm happy to change it to also reflect Go convention, but for now, maybe just leave the issue to track and revisit later?

**Comment by ss22ever** [comment]
Yes I believe the same.
