### ISSUE TITLE
validator.go: load schema from package in ValidateJSON

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#27]

**Comment by ss22ever** [comment]
@stp-ip could you please provide further explanation on this?

**Comment by ss22ever** [comment]
@stp So I assume [here](https://github.com/resumic/schema/blob/master/validator.go#L27) s is not a packr data?
I not so why do we need a function if it is getting loaded by itself?

**Comment by stp-ip** [comment]
So currently you load the schema into packr and read it from packr within the validate function. This means for any other function using that schema you need to do the same thing. It's not abstracted. The idea is to load the files examples + schema once into packr and then make the schema importable. That also would enable other developers to build on the schema by importing it.
