### ISSUE TITLE
Decision needed on adding various information fields to the sections

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#5]
Discussion needed on adding various information fields to the sections, vote for all that applies and needs discussion then we could open them up to separate issues and rediscuss.
1. - [x] Add credentials to references: Will it be nice to have the credential details like contact no of the referrer in the references section.
2. - [x] Add projects as a subsection to various sections of work, education, volunteer etc.
3. - [x] Add identifiers within publications e.g.  DOI, ISBN etc.
4. - [x] Put in a section for stand alone courses.Maybe helpful for those doing independent coursework and online courses.
5. - [x] Use schema.org vocabulary.
6. - [x] Add optional location to subsections.

**Comment by stp-ip** [comment]
1. I dislike credential details within the schema. I vote no. Easy to expose information we shouldn't expose. If someone wants to check a reference they should ask for the details beforehand. But that's my privacy concern speaking.

2. Would love your take on that. It might be great to have, but also complicates the schema. Considering that highlights could describe projects in one line, it might not be needed.

3. Hard to standardize right? But we could add it as an array and add the more standard identifiers and give it a dropdown in the editor or something.

4.  Seems like it could  be worked around by doing a catch-all education entity or actually list all courses by their single entities. I agree that the catch-all might be hacky and the single course per entity makes the resume horrible to read and also complicated. If you have a specific idea on how to structure this or maybe even do it within the education section, happy to see something providing more context.

5. Would love your fresh take on this.

6. Which subsections specifically and what would be the purpose for each of these? It might be valuable yes, but does it make sense in general or would it mostly complicated the schema?

**Comment by ss22ever** [comment]
1. -1 from my side too.Or maybe we could do a bit more of research to show this credential box to only those who actually need them?

**Comment by ss22ever** [comment]
2- Well according to me it will be great to have a separate projects section and in that, if we also add that of what the project was a part of education, volunteer etc and then show it on the theme grouped by the option selected?
e.g. projects marked with education on the education section and so on?

**Comment by ss22ever** [comment]
4- Maybe in the education section we could add independent coursework subsection that would be of the type array.

**Comment by stp-ip** [comment]
1. We can open an issue to discuss that after the first version, but it feels a huge burden to make it show to the right person. Especially considering that the most secure way to achieve that is not include the data.

2. I do feel it complicates the schema, but we could reduce the thinking burden in the editor by making it an advanced section or something. But I see why we might add that to the schema.

4. Seems like another thinking the user might have to do. Is it an actual education item or just additional course-work etc. Maybe have a generic entity or so per section to push these into. That way they have the same structure, but can be separated from projects/course-work related to a single entity.

**Comment by ss22ever** [comment]
4-But do you not feel the user still have to do the thinking to put which independent coursework to which section e.g. the user might be confused to put an online degree which he/she had in certifications or in education.

**Comment by stp-ip** [comment]
4 - I thought you wanted to layer the coursework section under the education section. So you want to keep it completely separate?
Then question would be, could we merge this into the projects section. I'm still trying to figure out the explicit need or if we could merge it into the current schema.
Maybe you have a specific example to showcase this better.
