### ISSUE TITLE
Discuss generic solutions for the following

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#6]
Discussion needed to find generic solutions of the following, vote for all that applies then we could open them up to separate issues and rediscuss.
1. - [x] Adding some personally identifiable information to the schema.This is a subject to internationalization and localization.
2. - [x] Find generic ways to support multiple languages over the schema which can further be used for converting to different forms of languages.This is a subject to internationalization.
3. - [x] Add additional personnel master data e.g. DOB,Citizenship etc.
4. - [x] To represent current work in the work section : 
           can we use endDate as null while having an option at the editor as "presently work here " that will  mark endDate as null by itself and can be updated anytime when it is no more an organization where the person currently works.

**Comment by stp-ip** [comment]
1. I don't like personally identifiable information, but in some countries it's necessary, but in some illegal. So I would move that into a special subsection. And in the editor hide it with a note that filling it out might not be necessary and asking for this data might also be illegal. Basically supporting people not knowing their rights. Might even link to some wikipedia site for clairification.

2. The best solution I found was actually having one base language and then substituting strings within the metadata section. Basically the base languages is the one holding the most data and the rest is basically string translation by a tool. Either this can be directly integrated into the editor ui or we provide a separate tool. In the issue there is one suggestion about how this might work in the metadata section.
Another idea was to use a separate schema file per language,. It makes the schema file itself cleaner, but might lead to outdated versions. Having one schema file we could easily notify the user that languages x and y are out of date and the following strings need to be translated or something like that.

3. Not sure on the specifics. Definitely would like more context on this.

Please also add your opinion and ideas. I might be biased having worked on it for a long time. So I might not see the easiest/best solution.

**Comment by ss22ever** [comment]
1- +1

**Comment by ss22ever** [comment]
2. I find the use of metadata section more appropriate as it does not create multiple schema files for the same data.Using multiple schema files for the same schema data would occupy more space in the storage in the long run for the data that we already have in one language.

**Comment by stp-ip** [comment]
1. Would say rediscuss after v1
