### ISSUE TITLE
Add credentials to references

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#7]
Will it be nice to have the credential details like contact no of the referrer in the references section?

**Comment by stp-ip** [comment]
Current stance is still that this shouldn't be handled within the schema as this is other people's private data and storing or sending such things around should be done out of band and on request.

**Comment by stp-ip** [comment]
Current decision is to not embed other people's private information in a resume or a data file that might be distributed widely. Name, company and title of the reference including the reference quote are embed and shown, but anything else such as phone number, email is private data and should be exchanged off record aka not within the resume.
