### ISSUE TITLE
2 more fields in the basic section of the schema

### ISSUE THREAD

**Issue by jphellemons** [resumic/schema#73]
As suggested here: https://github.com/jsonresume/resume-schema/issues/317

I'd like to add some fields to the basic part of the schema:

- place of birth or hometown
- birthday

Is there some documentation about how to proceed on this?

**Comment by stp-ip** [comment]
cc. @ArmanMazdaee

**Comment by stp-ip** [comment]
I think this is reasonable and could be implemented. One thing is to push this into a specific "personal" data section? So have one section with non identifying data and one with more personal data?
