### ISSUE TITLE
Add "version" command

### ISSUE THREAD

**Issue by stp-ip** [resumic/schema#76]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

Add version that either shows release and build commit for easier debugging.

**Comment by jahzielv** [comment]
[I've started to work on this](https://github.com/jahzielv/schema/commit/d109dc6a0718972e426476b16cb175f77cbfc8a6), but am wondering - where is the version information coming from? I see that there's a `VERSION` file in the root directory, which is what my sample command references, but was wondering if maybe you wanted build information or something else from GH, Travis, etc.

**Comment by stp-ip** [comment]
I think what would be helpful information is:
* application name: hardcoded/const set to "resumic"
* version: using -ldflags "-X $(go list -m)/resumic.Version=$(VERSION)" and populating this via the makefile, which can just read in the VERSION file
* platform such as "linux/amd64" (can be obtained by runtime.*)
* build version of go "go1.11.5" (can be obtained by runtime.*)
* git commit: using -ldflags `"-X $(go list -m)/resumic.GitCommit=$(GITCOMMIT)"` and `git describe --tags --always --dirty` to populate this variable within the makefile

Git is only necessary for dev builds and not release builds.
For dev builds we should add `-dirty` to the version.

For release builds we can check a variable such as "RELEASE" and see if it's true or not.
Default is false so to overwrite this we would need to run `make build RELEASE=true`.

That would be the rough idea. Happy for other suggestions and this got a bit more complicated than I first thought. Happy to help with any of the above ideas and concepts.

Also @ArmanMazdaee do you agree with the above?

**Comment by stp-ip** [comment]
Example of -ldflag usage: https://github.com/kubernetes/git-sync/blob/master/build/build.sh#L41
Example of populating GitCommit: https://github.com/coredns/coredns/blob/master/Makefile#L2

Coredns does hardcode the package import path. We probably should be using the clever approach as also used by git-sync, which is to get this import path from `go list -m`.

Some information about -ldflags: https://github.com/golang/go/wiki/GcToolchainTricks#including-build-information-in-the-executable

**Comment by jahzielv** [comment]
Ok, great! I'll start reading into `-ldflags` and how to bake this information into the build.

**Comment by jahzielv** [comment]
Should I make a PR now, or wait till I have some more viable code?

**Comment by stp-ip** [comment]
You can create a PR and we can iterate there. Always easier with inline comments etc.
If you have a PR that is a work in progress, you can add `[WIP]` to the title to indicate for reviewers that it's not finished yet or not ready for a merge.
When we want to finalize for a merge, we can rebase and squash/rename the specific commits to have a clean and good history.

**Comment by stp-ip** [comment]
Sidenote:
If resumic is installed via `go get` we don't have ldflags setting GitCommit or Version. Same, when built locally.

We could set defaults for the variables and then use ldflags to overwrite them on a release or binary build:

var (
	version = "dev"
	commit  = "none"
)

**Comment by jahzielv** [comment]
kinda silly question, but is the program going to be called resumic or schema? When I run `go install`, I get an executable called `schema`, but I'm not sure if that's correct.

**Comment by stp-ip** [comment]
It's called resumic, but by default go uses the name of the repository/directory, which in our case is schema.

You can define the output such as `go build -o resumic` to control the resulting name.
Also `go get` might use a vanity url so that the resulting binary is also called resumic: `go get go.resumic.org/resumic`

**Comment by stp-ip** [comment]
Sidenote: We are using go modules, which make the repository more selfcontained. That means there is no need to be forced to use the GOPATH for the repo.

**Comment by jahzielv** [comment]
Ok dope thanks for the info! 😄
