### ISSUE TITLE
Provide a seperate field in schema to store country code for contact number

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#8]
In case to internationalization many times it becomes difficult for employers to contact the person who has provided its contact info but not the country code for the same.
+49 --- Germany
+91 --- India
A better solution to this can be to have a predefined field for the country codes for the user to select in the editor.

**Comment by stp-ip** [comment]
Your suggestion would only affect the editor side right? The phone number would still be stored as usual?

**Comment by ss22ever** [comment]
Thought maybe we could use it as a separate field to let the dialers know about the country code.If included in the same it would need manipulation of the number.

**Comment by stp-ip** [comment]
Problem I see with a separate field is that we then have to normalize the phone number. Does it already come with + or 00 or without country code. etc. pp.

**Comment by ss22ever** [comment]
Maybe we could give a note on the editor side for this?

**Comment by stp-ip** [comment]
The phone number from the user should just be stored with a country code. The frontend could split this up, but that's an editor or theme concern.
