### ISSUE TITLE
Ability to set current for endDate on dates

### ISSUE THREAD

**Issue by stp-ip** [resumic/schema#82]
**Anything else we need to know?**:
How do we currently set a current endDate?
In my mind not setting an endDate would be enough to say current.

startDate set + endDate set -> range
startDate set + endDate unset -> range till current
startDate unset + endDate unset -> no range

Thoughts?

**Comment by injectedfusion** [comment]
Hi I'm interested in the project, after checking out JSONResume and saw this similar question wasn't resolved there. I am also in favor of not setting an endDate which implies it is current.
