### ISSUE TITLE
Add default values for cli

### ISSUE THREAD

**Issue by stp-ip** [resumic/schema#87]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently our default values for cli are not useful or not set.

**What you expected to happen**:
Make it easy to run "resumic generate example" etc. without setting the filename. similar idea for render and validate.

**Comment by jahzielv** [comment]
Would this be a good issue to work on next @stp-ip? Or is there something else in particular you'd like help with?

**Comment by stp-ip** [comment]
I think this sounds like a good next issue as this should let you figure out what the general CLI is doing and what defaults make sense so everything works as expected from a user point of view. As you are still quite unbiased in terms of using the CLI, this seems perfect.

**Comment by jahzielv** [comment]
After looking around, these are my thoughts:
- `generate` -> resume.json
- `generate example` -> example_resume.json
- `render`: looks for resume.json by default, outputs resume.html by default
- `validate`: looks for resume.json by default.

One thing we might want to consider as well is having a file naming convention that uses `resumic`'s name somehow. What do you think?

**Comment by stp-ip** [comment]
@ArmanMazdaee thoughts?

**Comment by stp-ip** [comment]
Only thing I would do differently due to language flow would be `resume_example.json`, but happy with your choice as well.

**Comment by jahzielv** [comment]
> Only thing I would do differently due to language flow would be `resume_example.json`

That sounds good to me! I'll start working on this.
