### ISSUE TITLE
[publications] Use date format for releaseDate

### ISSUE THREAD

**Issue by stp-ip** [resumic/schema#88]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
We are currently using string for releaseDate: https://github.com/resumic/schema/blob/master/schema.json#L527

**What you expected to happen**:
Use date format instead.

**Comment by jahzielv** [comment]
Seems like a quick fix! Does this need to be changed anywhere but `schema.go`?

**Comment by stp-ip** [comment]
Should only need changes in schema.go. The rest would be generated as far as I can see.
