### ISSUE TITLE
Rename releaseDate to publicationDate

### ISSUE THREAD

**Issue by stp-ip** [resumic/schema#89]
**Is this a BUG REPORT or FEATURE:
feature

**What happened**:
We currently use releaseDate within publications, but it feels like most publications use publicationDate and maybe creationDate, if it isn't released yet.

**What you expected to happen**:
Rename releaseDate to publicationDate.

**Anything else we need to know?**:
Maybe also add creationDate, but that might be unnecessary. I think renaming first and then iterate later seems good enough.

**Comment by jahzielv** [comment]
Seems like I could tackle this along with #88!

**Comment by stp-ip** [comment]
Sounds good.
