### ISSUE TITLE
Put a section for stand alone courses

### ISSUE THREAD

**Issue by ss22ever** [resumic/schema#9]
Maybe helpful for those doing independent coursework and online courses.
The idea is to have a separate section for all the independent coursework the person does.
That will be a separate section within itself.

**Comment by stp-ip** [comment]
Let's revisit this later. I feel this could be done in a custom education section.

**Comment by stp-ip** [comment]
Closing as this can be done via projects, certifications or education section.
If a separate section is needed, we should open this up for another discussion.
