### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by stp-ip** [resumic/schema#97]
docs/dev/* etc. seems unused or?

**Comment by jahzielv** [comment]
Yeah, I wondered about that before. Should we start some issues to being documentation, or should we wait until we have a more solid code base (and delete this unused stuff right now)?

**Comment by stp-ip** [comment]
I think we should wait a bit for the other code to mature before we jump into docs again.

As we have everything versioned, I gladly see any unused code removed sooner than later :)
